Final_Capstone/meal_planer/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
import uuid
from datetime import datetime


# adding Flask-Security for passwords
from werkzeug.security import generate_password_hash, check_password_hash

# import the secrets module (from Python) to generate a token for each user
import secrets

# import Flask-Login to check for an authenticated user and store the current user
from flask_login import UserMixin, LoginManager

# import Flask-Marshmallow to help create our Schemas
from flask_marshmallow import Marshmallow

db = SQLAlchemy()
login_manager = LoginManager()
ma = Marshmallow()


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(db.Model, UserMixin):
    id = db.Column(db.String, primary_key=True)
    first_name = db.Column(db.String(150), nullable=True, default='')
    last_name = db.Column(db.String(150), nullable=True, default='')
    email = db.Column(db.String(150), nullable=False)
    password = db.Column(db.String(150), nullable=True, default='')
    username = db.Column(db.String(150), nullable=True)
    token = db.Column(db.String, default='', unique=True)
    date_created = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    meal_plans = db.relationship('MealPlan', backref='owner', lazy=True)

    def __init__(self, email, username, first_name='', last_name='', password=''):
        self.id = self.set_id()
        self.first_name = first_name
        self.last_name = last_name
        self.password = self.set_password(password)
        self.email = email
        self.username = username
        self.token = self.set_token(24)

    def set_token(self, length):
        return secrets.token_hex(length)

    def set_id(self):
        return str(uuid.uuid4())

    def set_password(self, password):
        self.password = generate_password_hash(password)
        return self.password

    def __repr__(self):
        return f"User {self.email} has been added to the database!"


class MealPlan(db.Model):
    id = db.Column(db.String, primary_key=True)
    name = db.Column(db.String(150))
    description = db.Column(db.String(200), nullable=True)
    owner_token = db.Column(db.String, db.ForeignKey('user.token'), nullable=False)

    def __init__(self, name, description, owner_token):
        self.id = self.set_id()
        self.name = name
        self.description = description
        self.owner_token = owner_token

    def set_id(self):
        return str(uuid.uuid4())

    def __repr__(self):
        return f"MealPlan {self.name} has been added to the database!"


class MealPlanSchema(ma.Schema):
    class Meta:
        fields = ['id', 'name', 'description']


meal_plan_schema = MealPlanSchema()
meal_plans_schema = MealPlanSchema(many=True)

Final_Capstone/meal_planer/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, DecimalField
from wtforms.validators import DataRequired, Email

class UserLoginForm(FlaskForm):
    # email, password, submit_button
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators = [DataRequired(), Email()])
    password = PasswordField('Password', validators = [DataRequired()])
    submit_button = SubmitField()

Final_Capstone/meal_planer/__init__.py
from flask import Flask
from config import Config
from .site.routes import site
from .authentication.routes import auth
from .api.routes import api
from .models import db as root_db, login_manager
from flask_migrate import Migrate


from flask_login import LoginManager







from flask_cors import CORS
app = Flask(__name__)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)
app.config.from_object(Config)
root_db.init_app(app)

migrate = Migrate(app, root_db)




login_manager.init_app(app)
login_manager.login_view = 'auth.signin'




CORS(app)

# ... additional configuration and routes ...

Final_Capstone/meal_planer/api/routes.py
from flask import Blueprint, request, jsonify
from meal_planer.models import db

api = Blueprint('api', __name__, url_prefix='/api')



API_KEY = 'YOUR_SPOONACULAR_API_KEY'

def get_meal_data():
    url = 'https://api.spoonacular.com/recipes/random'
    params = {
        'apiKey':"e1794d5396a64d5e8a4767fe05db9565",
        'number': 3,  # Adjust the number of meals you want to retrieve
    }
    response = request.get(url, params=params)
    if response.ok:
        return response.json().get('recipes', [])
    return []

Final_Capstone/meal_planer/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from meal_planer.forms import UserLoginForm

from werkzeug.security import check_password_hash

from flask_login import login_user, logout_user, login_required, user_accessed, user_logged_in, user_login_confirmed 
from meal_planer.models import db,User

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            print(email, username)

            user = User(email, username, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f'You have succesfully created a user account {username}', 'user-created')

            return redirect(url_for('auth.signin'))
        
    except:
        raise Exception('Invalid Form Data: Please check your form') 
    return render_template('signup.html', form=form )

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()  

    try: 
        if request.method == 'POST' and form.validate_on_submit(): 
            email = form.email.data
            password = form.password.data
            print(email,password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                print(f"this is the logged user {logged_user}")
                login_user(logged_user)
                flash(f"You were successfully logged in: Via email/password", 'auth-success')
                return redirect(url_for('site.profile'))
            
            else:
               flash('Your email/password is incorrect', 'auth-failed')
               return redirect(url_for('auth.signin'))
        
    except:
        raise Exception('Invalid Form Data: Please Check Your Form!')

    return render_template('signin.html', form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

Final_Capstone/meal_planer/site/routes.py
from flask import Blueprint, render_template, session, redirect, url_for
from meal_planer.models import MealPlan
site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    print("ooga booga in the terminal")
    return render_template('index.html')


@site.route('/dashboard')
def dashboard():
   
    return render_template('profile.html')
   

Final_Capstone/meal_planer/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<l<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.main.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>meal planer API</title>

</head>
<body>
    <nav class="ct-nav">
        <div class="container">
            <a class="navbar-brand" href="#">Meal Planer</a>
           
            <div>
                <ul class="navbar-nav ml-auto">
                   
                    
                   

                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('site.dashboard')}}">Recipes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">LogOut</a>
                    </li>
                  
                   
                    

                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.signup') }}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.signin') }}">Sign In</a>
                    </li>
                    
                  
                    
                  
                </ul>
            </div>
        </div>
    </nav>
     <!-- End of Nav -->
     {% block content %}
     <!-- other content lives here -->
     {% endblock content %}
     
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script> 
</body>
</html>

Final_Capstone/meal_planer/templates/forms.html
<!-- HTML produced by the Flask Form -->
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="username-field">
            {{ form.username.label }}
            {{ form.username(class = "form-control", placeholder = "Place Username Here... ") }}
        </fieldset>
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Place Email Here... ") }}
        </fieldset>
        <fieldset id="password-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place Password Here... ") }}
        </fieldset>
        <!--Submit Button-->
        {{ form.submit_button(class="btn btn-primary btn-block mt-2") }}
    </div>
</form>